service: postingly-rest-api

plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  environment:
    STORES_TABLE: "Store"
    PROFILE_TABLE: "Profile"

functions:
  auth:
    handler: index.auth
    events:
      - http:
          path: /partners/{partner_slug}/auth
          method: get
          cors: true
  callback:
    handler: index.callback
    events:
      - http:
          path: /partners/{partner_slug}/callback
          method: post
          cors: true
  payment_return:
    handler: index.activatePayment
    events:
      - http:
          path: /partners/{partner_slug}/payment_return
          method: post
          cors: true

