service: postingly-rest-api

plugins:
  - serverless-plugin-warmup
  - serverless-prune-plugin
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  warmup:
    enabled: true
    folderName: '_warmup'
    cleanFolder: false
    memorySize: 256
    name: 'make-them-pop-rest-production'
    vpc:
      securityGroupIds:
        - sg-0e0b1c8b49a3919d8
      subnetIds:
        - subnet-0be2e1119f5a9942b
        - subnet-08f8f22623b8c212b
      
    events:
      - schedule: 'cron(*/3 * * * ? *)'
    timeout: 20
    prewarm: true
    concurrency: 1

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  timeout: 30 
  memorySize: 256
  vpc:
    securityGroupIds:
      - sg-0e0b1c8b49a3919d8
    subnetIds:
      - subnet-0be2e1119f5a9942b
      - subnet-08f8f22623b8c212b

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:*:* 
    - Effect: Allow
      Action:
        - cognito-identity:*
      Resource: 
        - arn:aws:cognito-identity:us-east-1:*:*
    - Effect: Allow
      Action:
        - cognito-sync:*
      Resource: 
        - arn:aws:cognito-sync:us-east-1:*:*
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: 
        - arn:aws:cognito-idp:us-east-1:*:*
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:us-east-1:*:* 

functions:
  auth:
    handler: index.auth
    events:
      - http:
          path: /partners/{partner_slug}/auth
          method: get
          cors: true
  callback:
    handler: index.callback
    events:
      - http:
          path: /partners/{partner_slug}/callback
          method: post
          cors: true
  payment_return:
    handler: index.activatePayment
    events:
      - http:
          path: /partners/{partner_slug}/payment_return
          method: post
          cors: true
  productsCreate:
    handler: index.productsCreate
    events:
      - http:
          path: /partners/{partner_slug}/productsCreate
          method: post
          cors: true
  productsUpdate:
    handler: index.productsUpdate
    reservedConcurrency: ${env:RESERVED_CONCURRENCY_WEBHOOK_UPDATE_PRODUCT}
    events:
      - http:
          path: /partners/{partner_slug}/productsUpdate
          method: post
          cors: true
  productsDelete:
    handler: index.productsDelete
    events:
      - http:
          path: /partners/{partner_slug}/productsDelete
          method: post
          cors: true
  collectionsCreate:
    handler: index.collectionsCreate
    events:
      - http:
          path: /partners/{partner_slug}/collectionsCreate
          method: post
          cors: true
  collectionsUpdate:
    handler: index.collectionsUpdate
    events:
      - http:
          path: /partners/{partner_slug}/collectionsUpdate
          method: post
          cors: true
  collectionsDelete:
    handler: index.collectionsDelete
    events:
      - http:
          path: /partners/{partner_slug}/collectionsDelete
          method: post
          cors: true
  appUninstalled:
    handler: index.appUninstalled
    events:
      - http:
          path: /partners/{partner_slug}/appUninstalled
          method: post
          cors: true
  shopUpdate:
    handler: index.shopUpdate
    events:
      - http:
          path: /partners/{partner_slug}/shopUpdate
          method: post
          cors: true
  twitterRequestToken:
    handler: index.twitterRequestToken
    events:
      - http:
          path: /twitter/getRequestToken
          method: post
          cors: true

