service: postingly-api-rest

plugins:
  - serverless-dotenv-plugin

  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  environment:
    STORES_TABLE: "Store"
    PROFILE_TABLE: "Profile"

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
