service: postingly-graphql
plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  timeout: 120 
  memorySize: 256
  vpc:
    securityGroupIds:
      - sg-0e0b1c8b49a3919d8
    subnetIds:
      - subnet-0be2e1119f5a9942b
      - subnet-08f8f22623b8c212b

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:*:* 
    - Effect: Allow
      Action:
        - ec2:DescribeNetworkInterfaces
        - ec2:CreateNetworkInterface
        - ec2:DeleteNetworkInterface
        - ec2:DescribeInstances
        - ec2:AttachNetworkInterface
      Resource:
        - arn:aws:lambda:us-east-1:*:*
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:us-east-1:*:*  
  

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true  
      - http:
          path: graphql
          method: get
          cors: true  
