service: postingly-graphql
plugins:
  # - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

# custom:
#   webpack:
#     webpackConfig: ./webpack.config.js
#     includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  environment:
    STORES_TABLE: "Store"
    PROFILE_TABLE: "Profile"

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get
