service: postingly-graphql
plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:*:* 
  environment:
    STORES_TABLE: "Store"
    PROFILE_TABLE: "Profile"

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true  
      - http:
          path: graphql
          method: get
          cors: true  
