service: postingly-graphql
plugins:
  - serverless-prune-plugin
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: us-west-2
  timeout: 30 
  memorySize: 256
  vpc:
    securityGroupIds:
      - sg-0f4152f35882c4eb3
    subnetIds:
      - subnet-0c928dbe126d885eb
      - subnet-067027d8f3d3197fc

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-west-2:*:* 
    - Effect: Allow
      Action:
        - ec2:DescribeNetworkInterfaces
        - ec2:CreateNetworkInterface
        - ec2:DeleteNetworkInterface
        - ec2:DescribeInstances
        - ec2:AttachNetworkInterface
      Resource:
        - arn:aws:lambda:us-west-2:*:*
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:us-west-2:*:*  
  

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true  
      - http:
          path: graphql
          method: get
          cors: true  
