service: postingly-graphql
plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  vpc:
    securityGroupIds:
      - sg-6e86951d
    subnetIds:
      - subnet-4673b90d
      - subnet-46d56622
      - subnet-68321e64

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:*:* 
  

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true  
      - http:
          path: graphql
          method: get
          cors: true  
