service: postingly-functions

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

functions:
  post-updates:
    handler: postUpdates.share
    events:
      - schedule:
          rate: cron(*/5 * * * ? *)
          enabled: true
  data-seed:
    handler: seeddata.createStore
  data-test:
    handler: seeddata.testData
  cognito-create-auth-challenge:
    handler: cognito.createAuthChallenge
  cognito-define-auth-challenge:
    handler: cognito.defineAuthChallenge
  cognito-verify-auth-challenge:
    handler: cognito.verifyAuthChallenge

  create-updates:
    handler: createUpdates.createUpdates
