service: postingly-functions

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

functions:
  cron-post-updates:
    handler: cronPostUpdates.share
    events:
      - schedule:
          rate: cron(*/5 * * * ? *)
          enabled: true
  cron-this-week-rules:
    handler: cronThisWeekRulesForUpdates.excute
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true
  cron-add-captions:
    handler: cronAddCaptions.execute
    events:
      - schedule:
          rate: cron(*/5 * * * ? *)
          enabled: true
  sync-store-data:
    handler: syncStoreData.syncStoreData
  sync-collections:
    handler: syncStoreData.syncCollections
  sync-collection-page:
    handler: syncStoreData.syncCollectionPage
  sync-products:
    handler: syncStoreData.syncProducts
  sync-product-page:
    handler: syncStoreData.syncProductPage
  data-seed:
    handler: seeddata.createStore
  data-test:
    handler: seeddata.testData
  cognito-create-auth-challenge:
    handler: cognito.createAuthChallenge
  cognito-define-auth-challenge:
    handler: cognito.defineAuthChallenge
  cognito-verify-auth-challenge:
    handler: cognito.verifyAuthChallenge

  create-updates:
    handler: createUpdates.createUpdates
  schedule-updates:
    handler: ScheduleProductUpdates.schedule
