service: postingly-functions

plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  vpc:
    securityGroupIds:
      - sg-0e0b1c8b49a3919d8
    subnetIds:
      - subnet-0be2e1119f5a9942b
      - subnet-08f8f22623b8c212b

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:*:* 
functions:
  # create update lambda. this function recieves rule id from either 
  # manage rule resolver or from cron-create-updates-for-next-week lambda function. 
  # this function creates updates with rule id. 
  create-updates:
    handler: createUpdates.createUpdates
  # creates update for the next week. this lambda will execute on every 
  # wednesday midnight
  cron-create-updates-for-next-week:
    handler: createUpdates.createUpdatesforNextWeek
    events:
      - schedule:
          rate: cron(0 0 ? * WED *)
          enabled: true
  # this lambda executes everyday at UTC midnight and pass distinct rule 
  #  based on the updates that are not scheduled. 
  cron-this-week-rules:
    handler: cronThisWeekRulesForUpdates.excute
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true
  # This updates simply takes the rule id and schedule all the not scheduled updates. 
  schedule-updates:
    handler: scheduleProductUpdates.schedule
  # This lambda takes the cron and add captions to the scheduled updates. plus also approve them. 
  cron-add-captions:
    handler: cronAddCaptions.execute
    events:
      - schedule:
          rate: cron(*/5 * * * ? *)
          enabled: true
  # This updates simply takes the rule id and schedule all the not scheduled updates. 
  change-caption:
    handler: changeCaption.update
  # this lambda runs every 5 minutes and call share-updates lambda to post updates. 
  cron-post-updates:
    handler: cronPostUpdates.share
    events:
      - schedule:
          rate: cron(*/5 * * * ? *)
          enabled: true
  # This lambda post updates to social media. 
  share-updates:
    handler: shareUpdates.share
  
  
  
  #  product sync data.
  sync-store-data:
    handler: syncStoreData.syncStoreData  
  sync-collections:
    handler: syncStoreData.syncCollections
  sync-collection-page:
    handler: syncStoreData.syncCollectionPage
  sync-products:
    handler: syncStoreData.syncProducts
  sync-product-page:
    handler: syncStoreData.syncProductPage
  get-webhooks:
    handler: webhooks.getWebhooks
  data-seed:
    handler: seeddata.createStore
  data-test:
    handler: seeddata.testData
  rule-test:
    handler: seeddata.testRules
  fetch-test:
    handler: seeddata.testFetch
  
  # cognito 
  cognito-create-auth-challenge:
    handler: cognito.createAuthChallenge    
  cognito-define-auth-challenge:
    handler: cognito.defineAuthChallenge    
  cognito-verify-auth-challenge:
    handler: cognito.verifyAuthChallenge    

  
  
  # Testing The Lambdas
  test-lambda:
    handler: lambdaTests.execute
  test-webhooks-lambda:
    handler: lambdaWebhooksTests.execute
  test-sync-lambda:
    handler: lambdaSyncTests.execute
